<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{
    /**
     * Get all projects withing a workspace.
     *
     * @param int|null $workspaceId
     *   The ID of the workspace to get projects for. Or null.
     *
     * @return array
     */
    public function getAllProjects($workspaceId = null)
    {
        $q = $this->createQueryBuilder('p');

        // Filter by workspace ID if present.
        if (!empty($workspaceId)) {
            $q->where('p.workspace = :workSpaceId');
            $q->setParameter('workSpaceId', $workspaceId);
        }

        return $q->getQuery()->getResult();
    }
}
