imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@MyBundle/Resources/config/services.yml" }
    - { resource: sonata_classification.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"
        types:
            json: Sonata\Doctrine\Types\JsonType

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                mappings:
                    ApplicationSonataMediaBundle: ~
                    SonataMediaBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# FOSUserbundle
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User

# Sonata
sonata_admin:
    title: MAVA v1.0
    title_logo: img/mava-logo-small.png
sonata_block:
    default_contexts: [cms]
    blocks:
        # Enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]
sonata_media:
    # if you don't use default namespace configuration
    #class:
    #    media: MyVendor\MediaBundle\Entity\Media
    #    gallery: MyVendor\MediaBundle\Entity\Gallery
    #    gallery_has_media: MyVendor\MediaBundle\Entity\GalleryHasMedia
    db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr it is mandatory to choose one here
    default_context: default # you need to set a context
    contexts:
        default:  # the default context is mandatory
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
                - sonata.media.provider.vimeo

            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}

    cdn:
        server:
            path: /uploads/media # http://media.sonata-project.org/

    filesystem:
        local:
            directory:  "%kernel.root_dir%/../web/uploads/media"
            create:     false

assetic:
    debug:          "%kernel.debug%"
    use_controller: "%kernel.debug%"
    filters:
        cssrewrite: ~
        less:
            node: /usr/bin/node
            node_paths: [/usr/lib/node_modules]
            apply_to: '\.less$'
    assets:
        mava_css:
            inputs:
                - "%kernel.root_dir%/Resources/public/css/mava.css"
            filters:
                - less
                - cssrewrite
            output: css/mava.css
        mava_js:
            inputs:
                - "%kernel.root_dir%/Resources/public/js/mava.js"
            output: js/mava.js
        fontAwesome_css:
            inputs:
                - "%kernel.root_dir%/Resources/public/font-awesome-4.1.0/css/font-awesome.css"
            filters:
                - less
                - cssrewrite
            output: css/font-awesome.css
        fontAwesome_eot:
            inputs: "%kernel.root_dir%/Resources/public/font-awesome-4.1.0/fonts/fontawesome-webfont.eot"
            output: fonts/fontawesome-webfont.eot
        fontAwesome_svg:
            inputs: "%kernel.root_dir%/Resources/public/font-awesome-4.1.0/fonts/fontawesome-webfont.svg"
            output: fonts/fontawesome-webfont.svg
        fontAwesome_ttf:
            inputs: "%kernel.root_dir%/Resources/public/font-awesome-4.1.0/fonts/fontawesome-webfont.ttf"
            output: fonts/fontawesome-webfont.ttf
        fontAwesome_woff:
            inputs: "%kernel.root_dir%/Resources/public/font-awesome-4.1.0/fonts/fontawesome-webfont.woff"
            output: fonts/fontawesome-webfont.woff
        FontAwesome_otf:
            inputs: "%kernel.root_dir%/Resources/public/font-awesome-4.1.0/fonts/FontAwesome.otf"
            output: fonts/FontAwesome.otf
        metisMenu_css:
            inputs:
                - "%kernel.root_dir%/Resources/public/css/plugins/metisMenu.css"
            filters:
                - less
                - cssrewrite
            output: css/metisMenu.css
        metisMenu_js:
            inputs:
                - "%kernel.root_dir%/Resources/public/js/plugins/metisMenu.js"
            output: js/metisMenu.js
        morris_css:
            inputs:
                - "%kernel.root_dir%/Resources/public/css/plugins/morris.css"
            filters:
                - less
                - cssrewrite
            output: css/morris.css
        morris_js:
            inputs:
                - "%kernel.root_dir%/Resources/public/js/plugins/morris/morris.js"
                - "%kernel.root_dir%/Resources/public/js/plugins/morris/morris-data.js"
                - "%kernel.root_dir%/Resources/public/js/plugins/morris/raphael.min.js"
            output: js/morris.js
        bootstrap_fonts_eot:
            inputs: "%kernel.root_dir%/../vendor/twbs/bootstrap/fonts/glyphicons-halflings-regular.eot"
            output: fonts/glyphicons-halflings-regular.eot
        bootstrap_fonts_svg:
            inputs: "%kernel.root_dir%/../vendor/twbs/bootstrap/fonts/glyphicons-halflings-regular.svg"
            output: fonts/glyphicons-halflings-regular.svg
        bootstrap_fonts_ttf:
            inputs: "%kernel.root_dir%/../vendor/twbs/bootstrap/fonts/glyphicons-halflings-regular.ttf"
            output: fonts/glyphicons-halflings-regular.ttf
        bootstrap_fonts_woff:
            inputs: "%kernel.root_dir%/../vendor/twbs/bootstrap/fonts/glyphicons-halflings-regular.woff"
            output: fonts/glyphicons-halflings-regular.woff
        bootstrap_css:
            inputs:
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/less/bootstrap.less"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/dist/css/bootstrap-theme.css"
            filters:
                - less
                - cssrewrite
            output: css/bootstrap.css
        bootstrap_js:
            inputs:
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/transition.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/alert.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/button.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/carousel.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/collapse.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/dropdown.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/modal.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/tooltip.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/popover.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/scrollspy.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/tab.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/affix.js"
            output: js/bootstrap.js
        jquery:
            inputs:
                - "%kernel.root_dir%/Resources/public/js/jquery-2.2.2.min.js"
            output: js/jquery.js

mopa_bootstrap:
    form: ~ # Adds twig form theme support
    menu: ~ # Enables twig helpers for menu