# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    admin.workspace:
        class: AppBundle\Admin\WorkspaceAdmin
        arguments: [~, AppBundle\Entity\Workspace, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Workspace, group: Content }

    admin.project:
        class: AppBundle\Admin\ProjectAdmin
        arguments: [~, AppBundle\Entity\Project, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Project, group: Content }

    admin.task:
        class: AppBundle\Admin\TaskAdmin
        arguments: [~, AppBundle\Entity\Task, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Task, group: Content }
        calls:
            - [ setTranslationDomain, [AppBundle]]

    mava_util:
        class: AppBundle\Util\Mava
        arguments: ['@doctrine.orm.entity_manager']

